Repository IvanKuchin/einsteiners.us, pull requests merged in 2022-02, with the labels that each got.

#76 Infrastructure: bugfix in github action release-drafter
  .github/workflows/release-drafter.yml
Labels: bugfix, infrastructure

#77 Infrastructure: prettify release-drafter
  .github/actions/release-drafter/release-drafter.yml
Labels: infrastructure

#78 Infrastructure: fixing package publishing
  .github/workflows/release-deployment.yml
  docker/Dockerfile
Labels: bugfix, infrastructure

#79 Infrastructure: bugfix in github action deployment
  .github/workflows/release-deployment.yml
Labels: bugfix, infrastructure

#80 Infrastructure: bugfix in github action deployment
  .github/workflows/release-deployment.yml
  docker/Dockerfile
Labels: bugfix, infrastructure

#81 Infrastructure: bugfix in github action deployment
  docker/Dockerfile
Labels: bugfix, infrastructure

#82 Infrastructure: bugfix in github action deployment
  .github/workflows/release-deployment.yml
Labels: bugfix, infrastructure

#83 Infrastructure: bugfix in github action deployment
  docker/Dockerfile
Labels: bugfix, infrastructure

#84 Infrastructure: change auth token to GITHUB_TOKEN
  .github/workflows/release-deployment.yml
Labels: infrastructure

#86 Infrastructure: test stage deployment
  .github/workflows/stage-deployment.yml
  docker-compose.yml
Labels: infrastructure

#91 Fixing video issue
  1111111111
Labels: bugfix

#93 Infrastructure: add git_commit_id to be visible
  1111111111
  docker/Dockerfile
  public/manifest.json
Labels: infrastructure

#117 Infrastructure: container regenerates .env on run
  docker/Dockerfile
  docker/entrypoint.sh
Labels: infrastructure

#123 Bugfix: docker file incorrectly filling commit_id-file
  docker/Dockerfile
Labels: bugfix
